name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./dave-kav

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm ci

      - name: Type Check
        run: npx tsc --noEmit

      - name: Build React App
        run: npm run build

      - name: Compile LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          root_file: dave-kav/src/assets/resume/resume.tex

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: resume.pdf
          path: resume.pdf

      - name: Download PDF to build directory
        uses: actions/download-artifact@v4
        with:
          name: resume.pdf
          path: dave-kav/build

      - name: Create CNAME
        run: echo "www.dave-kav.com" > build/CNAME

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dave-kav/build
          branch: gh-pages
          clean: true

permissions:
  contents: write
